# Generated by Django 4.1 on 2022-08-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('Fecha_de_nacimiento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Familiares',
        ),
    ]
