# Generated by Django 4.1 on 2022-08-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0002_familia_delete_familiares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='Fecha_de_nacimiento',
            new_name='nacimiento',
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
